### PR TITLE
Add support for room version 7

### PR DESCRIPTION
**Pull request by richvdh**

### CODE REVIEW

**Comment by richvdh** [comment]
CI seems to be failing on something unrelated?

**Comment by kegsay** [comment]
So room version 6 == 7 ?

**Comment by kegsay** [comment]
> CI seems to be failing on something unrelated?

yeah, for some reason `malign` is enabled for CI :/ ignore it and I'll fix it.

**Comment by richvdh** [comment]
> So room version 6 == 7 ?

well, the only difference (per [MSC2998](https://github.com/matrix-org/matrix-doc/blob/anoa/room_version_7/proposals/2998-rooms-v7.md)) is that it allows `knock` memberships, which isn't something that gomatrixserverlib currently cares about.

**Review by kegsay — APPROVED** [review]

**Pull request merged**
