### PR TITLE
Add AS dummy device ID

### PR DESCRIPTION
**Pull request by APwhitehat**
Required to have a common device ID for all AS.

`Signed-off-by: Anant Prakash <anantprakashjsr@gmail.com>`

### CODE REVIEW

**Comment by anoadragon453** [comment]
Might want to stick in [appservice.go](https://github.com/matrix-org/gomatrixserverlib/blob/master/appservice.go) btw.

**Comment by APwhitehat** [comment]
@anoadragon453 yeah. Should have fetched upstream before making a new file.

**Comment by anoadragon453** [comment]
Looking at this again, I'm not sure if this is something that belongs in gomatrixserverlib, only because I'm not sure other matrix go server implementation really need this?

**Comment by APwhitehat** [comment]
closed in favour of  matrix-org/dendrite#487

**Pull request closed without merging**
